### ISSUE TITLE
How to Use my RDP ? :/

### ISSUE THREAD

**Issue by Snipy44** [ionuttbara/melody_windows#11]
![image](https://github.com/ionuttbara/melody_windows/assets/3805333/793c5419-ee29-4736-aed6-ae29f757af3f)

Hello i have this problem how ro resolved this pleas ?

**Comment by ionuttbara** [comment]
if you use Canary Channel , you'll see in source code this script unregisters RDP classes due Microsoft Depreciation. To get back check policy group and re-register RDP.
Before to apply the script, you can create own version by excluding RDP removal such services and classes.
