### ISSUE TITLE
VPN dont work anymore after runnidng the script

### ISSUE THREAD

**Issue by redline99cs** [ionuttbara/melody_windows#13]
my vpn software doesnt work anymore after running the windows exe file for the scripts,
i use surfshark and keepa vpn unlimited, my network symbol goes to offline any help appreciated as i like the scripts but i need to use vpn software,
i already tried to reset my network adapter without help
thanks for help

**Comment by ionuttbara** [comment]
what vpn software are you using?
vpn was tested with P2TP Configuration (Windows VPN Client).
