### ISSUE TITLE
How to reset please help

### ISSUE THREAD

**Issue by Syed123221** [ionuttbara/melody_windows#15]
Hi , after running the file back then caused issue alot to my pc it cant reset , cant run sfc scan please help me to revert change its serious issue please .
[melody_windows-main.zip](https://github.com/ionuttbara/melody_windows/files/14001871/melody_windows-main.zip)

**Comment by VaporeonScripts** [comment]
now fortnite lags even more the fps, how can i fix?

**Comment by Syed123221** [comment]
> now fortnite lags even more the fps, how can i fix?

What?

**Comment by evlo** [comment]
> Hi , after running the file back then caused issue alot to my pc it cant reset , cant run sfc scan please help me to revert change its serious issue please . [melody_windows-main.zip](https://github.com/ionuttbara/melody_windows/files/14001871/melody_windows-main.zip)

sadly you would need to go script by script, i think better reinstall os if you did not do restore point

**Comment by Syed123221** [comment]
> > Hi , after running the file back then caused issue alot to my pc it cant reset , cant run sfc scan please help me to revert change its serious issue please . [melody_windows-main.zip](https://github.com/ionuttbara/melody_windows/files/14001871/melody_windows-main.zip)
> 
> sadly you would need to go script by script / reg by reg, i think better reinstall os if you did not do restore point

I tried everything possible didn’t work it doesn’t reset doesn’t let reinstall os anything bruh it made like malware or virus pc no work only opens and lags even I went to service centre no help

**Comment by evlo** [comment]
I agree, but it is our own stupidity that se did run it.

In my case I found it as I was trying to disable defender, which I still think acts more like a malware then this. Ok maybe same as this all things considered.

I'm only mad at myself for running this , for running this on my regular pc even.
It would be nice of autor to describe what this really is on GitHub and on program start  but ultimately out faut for being stupid starting this.
