### ISSUE TITLE
no internet connection showing up on windows but there is an internet connection

### ISSUE THREAD

**Issue by kops1330** [ionuttbara/melody_windows#16]
on my taskbar it says no internet connection but im connected i can still use everything normally except for spotify and uwp apps..
![image](https://github.com/ionuttbara/melody_windows/assets/159491715/a93b48a4-291a-4bc8-a1c5-ac0f04aa5fd4)

**Comment by ionuttbara** [comment]
what version of Windows 10 are you using?

**Comment by kops1330** [comment]
the latest 22h2 with all updates installed with the build 19044.3086

**Comment by ionuttbara** [comment]
resetting wmi can help. in Windows 10 the internet connection indicators using WMI, but thx for info.

**Comment by ionuttbara** [comment]
starting in version 15.0 and newer installations of Windows, Melody Script will not broke WMI. i take this kinda fixed.
