### ISSUE TITLE
I can't run Script. Pls help me

### ISSUE THREAD

**Issue by Trum00thay** [ionuttbara/melody_windows#2]
![image](https://github.com/jbara2002/melody_windows/assets/94278690/501588b0-c876-4aed-9b56-24741c77e9e6)

**Comment by Angsimosaurus** [comment]
The same problem happened to me.
I hope it's resolved soon.😂

<img width="735" alt="1" src="https://github.com/jbara2002/melody_windows/assets/79510039/1d83262a-66c4-49cb-9b61-73f96fc23359">

**Comment by anasemadanas** [comment]
not work in windows 11 
![image](https://github.com/jbara2002/melody_windows/assets/18718337/eaa5d7e7-ad98-48a1-b1d3-d71fbd24d714)

**Comment by Trum00thay** [comment]
LOL

**Comment by PythonicBoat** [comment]
![image](https://github.com/ionuttbara/melody_windows/assets/68675629/d3161233-af5b-43fb-99ab-6e69ffda2c70)
The script is identified as a Virus on windows 11 version 22H2 22621.2070

**Comment by ionuttbara** [comment]
is identified as virus because it has microsoft websites which can host telemetry. i'll deprecate soon and that will not be detected soon as virus.
