### ISSUE TITLE
Computer gets stuck when starting games

### ISSUE THREAD

**Issue by ZL666OY** [ionuttbara/melody_windows#20]
Computer gets stuck when starting games release **15.0.1**
The reason is DWM, fix it. Make a stable version.
Tired of reinstalling Windows every time

**Comment by ionuttbara** [comment]
remove directory HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm from registry editor and reboot.

**Comment by ZL666OY** [comment]
Deleted it, didn't help

**Comment by ionuttbara** [comment]
what gpu do you have?

**Comment by ionuttbara** [comment]
and also: what game had you tried to play? 
does the game uses directx 12?

**Comment by ZL666OY** [comment]
6800 ht. Any game no matter what DirectX

**Comment by ionuttbara** [comment]
in dwm its a problem with CpuCicling Value and it breaks directx12. thats why i asking you. but in vm i dont get that so easily.

**Comment by ionuttbara** [comment]
can you name the game? i want to test more specific.

**Comment by ZL666OY** [comment]
> можете назвать игру? я хочу протестировать более конкретно.
Cs2, fortnite, war tunder.

**Comment by ionuttbara** [comment]
> > можете назвать игру? я хочу протестировать более конкретно.
> > Cs2, fortnite, war tunder.

hm.... CS2, fortnite... 
i play these games and i don't have any encountered problems. i playing on AMD and Nvidia GPU, so exactly idk.
i thought this thing was a DX12 problem, not DX11. so i will close this issue for now.
