### ISSUE TITLE
DWM potential issue with NV GPU

### ISSUE THREAD

**Issue by velaar** [ionuttbara/melody_windows#25]
These is a kind of issue that makes me wish the EventViewer was operational. 

When switching to full screen playing a video H.265 or H.264 NVidia driver crashes to black screen. Network becomes unresponsive so can't see what actually is happening. The issue seems intermittent and comes after long watching sessions. 

Resetting DWM to stock on W11 23H2 seems to fix the issue. So it is likely DWM reg. pending further testing. 

Set up is RTX 4090 connected via 48Gbit HDMI to LG C1 TV so Gsync + HDR + 12bit RGB. The crash seems to happen on full screen only so suspect modesetting. 

@ionuttbara  anything in your experience that I should try to diagnose further?

**Comment by ionuttbara** [comment]
hi @velaar ! thx for reporting the issue.
i will check this and testing.

**Comment by ionuttbara** [comment]
fixed in 15.3 third release. you must remove dwm configuration from ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm``` and apply it again. if any problem persists feel free to re-open the issue.

**Comment by velaar** [comment]
@ionuttbara  
![image](https://github.com/ionuttbara/melody_windows/assets/4062230/83055a5b-495d-47bf-9847-e08260bff844)
Looks like the changes didn't go through. What was the change exactly?

**Comment by ionuttbara** [comment]
in realeae file.

**Comment by ionuttbara** [comment]
go to release -> change some values in dwm_registry.reg remove some ddraw usage conf. in dwm.

**Comment by ionuttbara** [comment]
https://github.com/ionuttbara/melody_windows/releases/tag/release153_3

**Comment by velaar** [comment]
@ionuttbara  The most recent release crashed again. Looks like EnableDrawToBackbuffer=1 is not compatible with my GPU. Added to my overrides. Consider removing in the next update

**Comment by ionuttbara** [comment]
how to get that to crash? i need more details.

**Comment by velaar** [comment]
Re-closing. Apparently nVidia is doing something weird with the Nvidia Frame View SDK via Nvidia app there. Can't reproduce without the app. Seems to crash on a desktop -> full screen transition (example - playing a video full screen or launching a game in a non-borderless mode). Went away from Nvidia app in favour of Nvidia Profile Inspector and NvTrueHDR as RTX HDR is nice. :) 

On a bright side Nvidia app also does not work with blocked internet access causing more delays/issues. 

Hope this comment helps.

**Comment by velaar** [comment]
Closed as per comment above

**Comment by velaar** [comment]
@ionuttbara 

Alright, back at it. After a LOT of testing and finally finding a reproduceable-enough nvkern crash I can report that  _**some**_ games _**some**_ times crash if 

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm]
"ParallelModePolicy"=dword:00000002
```

No crash with "ParallelModePolicy"=dword:00000001 or "ParallelModePolicy"=dword:00000004. I know that 0,1,2,4 are legit settings. But do you have any source info on what this parameter does exactly? I currently set it to 4 for testing. 

Note: the game that reliably crashes for me on launch with it set to 2 is StarCraft 2.
