### ISSUE TITLE
Disable grouping of taskbar icons in Windows 11

### ISSUE THREAD

**Issue by ghost** [ionuttbara/melody_windows#26]

**Comment by ionuttbara** [comment]
give me a clear list of settings and if that is or not from StartAllBack to add a list for you there.

**Comment by ZL666OY** [comment]
> дайте мне четкий список настроек и, если это есть или нет, из StartAllBack, чтобы добавить список для вас туда.

After using the script, never merge icons is disabled, looks terrible
![FLqMRIe](https://github.com/ionuttbara/melody_windows/assets/16303479/ee26b475-2cf8-4832-b669-4ef3579d7865)

**Comment by ionuttbara** [comment]
closed to inactivity of response
