### ISSUE TITLE
Unable to type while using UWP apps

### ISSUE THREAD

**Issue by kops1330** [ionuttbara/melody_windows#28]
Whenever i use a UWP app such as the Microsoft sign in, Xbox,settings and Microsoft store, i am unable to type at all, it will type fine at any other program that is not a UWP application, however nothing registers when using a UWP app

**Comment by ionuttbara** [comment]
what version of Windows is that?

**Comment by kops1330** [comment]
> what version of Windows is that?

the latest windows 10 22h2 build

**Comment by ionuttbara** [comment]
looking for issue.

**Comment by ionuttbara** [comment]
found.
change start of Touch Keyboard and Handwriting Panel Service to automatic.
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TextInputManagementService]
"Start"=dword:00000002
