### ISSUE TITLE
I can't activate Wake On Lan on my Ethernet device after applying the Script

### ISSUE THREAD

**Issue by paQ75** [ionuttbara/melody_windows#3]
Hello. I have applied the Script and I have two problems. The first is that the option to 'allow this device to wake up the system' on the device manager/ethernet device/energy administration, is greyed out (don't have permissions for change this?). The second is that when I click on the context menu after selecting several files on the windows explorer it takes almost 1 minute to show the menu. Any solutions?

**Comment by ionuttbara** [comment]
1. The loading menu problem is reported.
2."Allow this device to wake up the system" is not a policy. Try to run this command
``` powercfg -devicedisablewake "name of your network adapter" ``` 
in cmd.
