### ISSUE TITLE
Firefox crashing when downloading anything from the internet

### ISSUE THREAD

**Issue by kops1330** [ionuttbara/melody_windows#30]
Hi,

As the title says Firefox crashes whenever i download anything at all no matter the file type and the file size, also trying to change the location of where files are saved will result in firefox crashing, i am on the latest Windows 10 build 19045.2965 as of now, however this does not happen on any other chromium browser or chrome as a whole

**Comment by kops1330** [comment]
https://github.com/ionuttbara/melody_windows/assets/159491715/e0a204b3-be9c-42fe-89e3-d207f518def7

**Comment by ionuttbara** [comment]
maybe was from folder integration? i use firefox and i did not have problems. can you say what windows version do you have?

**Comment by kops1330** [comment]
, i am on the latest Windows 10 build 19045.2965
