### ISSUE TITLE
file explorer doesnt show my downloads folder

### ISSUE THREAD

**Issue by kops1330** [ionuttbara/melody_windows#31]
Hi,

When i open file explorer it only shows my drives and not my folders unlike windows 11 where it showed my downloads,photos and videos folder i have to manually press on view then options then press change folder and search options then press view then press show all folders which only shows my user folder but when i click on it shows my downloads and other folders
![image](https://github.com/ionuttbara/melody_windows/assets/159491715/85380141-e33b-4319-a7d0-02778deb2328)

**Comment by kops1330** [comment]
temporarily on stock win11 until program is stable

**Comment by kops1330** [comment]
if possible can you add a feature where UAC can be re enabled, i try to reenable it and it crashes my explorer everytime

**Comment by ionuttbara** [comment]
noted as bug.

**Comment by kops1330** [comment]
Hi, the bug is still present on the latest 24h2 as i tested it in a virtual machine and my explorer is still the same as before 
![{594F3172-9756-401E-B439-A2B4945C3D92}](https://github.com/user-attachments/assets/45a6d7ec-342a-44b0-8695-b7d5908e3e3d)
