### ISSUE TITLE
UTILITY disable my ethernet afterwards

### ISSUE THREAD

**Issue by Antonia01020394** [ionuttbara/melody_windows#34]
ive executed the utility  restarted and ive found out my ethernet wasnt getting connected to the internet

**Comment by velaar** [comment]
This is not an expected behaviour, however with a one-liner it's hard to help here. Do you know what exactly broke it? What is your networking card setup / configuration? 

Also did that behaviour show up during your testing? 

A kind reminder from Readme: 
```
WARNING:
When you run this script it will change A LOT of windows preferences to the liking of autor of this script, Once executing the exe, it does start, it does not ask for anything and there is NO WAY TO ROLLABACK the changes. Proceed with extreme caution. Try in VM. Extract the source and use individual files. Before to open the app, extract with WinRAR or 7-Zip and remove the unwanted tweaks/registry files. There are organized in Settings folder.

```

**Comment by Antonia01020394** [comment]
it just disabled my ethernet services or smth like that
my pc was fine, aside from overtweaked (still regular) but it was a unexpected thing

**Comment by ionuttbara** [comment]
it removes Integrated Windows Network Drivers which are FoD since Windows 11 21H2 or newer, to be lightweight. A backup of network drivers is recommended if you apply on clean installion of Windows. These network drivers are removed via PowerShell.

**Comment by Antonia01020394** [comment]
How do I restore them?

**Comment by ionuttbara** [comment]
redownloading the network drivers from manufacturer website.

**Comment by Antonia01020394** [comment]
Hold on, you want ME to install them when I don't have internet?
