### ISSUE TITLE
Black Screen when launching a game.

### ISSUE THREAD

**Issue by LoMce** [ionuttbara/melody_windows#36]
Just recently tried using melody tweaks but after using them anytime i launch a game after 2-3 seconds the screen just turns black, Not able to tab out neither open task manager the only solution is to turn my pc off manually. Tried using variety of different versions of windows 10 and 11 but all give the same result. Is there a way to fix that ? Because These tweaks make my pc super fast and snappy and i like it alot i just have this 1 problem.

**Comment by LoMce** [comment]
delete this from regedit and everything is working now! wish the dwm tweaks would work without issues.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Dwm

**Comment by velaar** [comment]
I wonder if it is the memory policy. Try setting it to 4. It's the only DWM tweak I had to override to make everything work.

Sent from Proton Mail Android

-------- Original Message --------

**Comment by LoMce** [comment]
yes setting ParallelModePolicy to 4 also fixed it.
