### ISSUE TITLE
I want to re-enable some features

### ISSUE THREAD

**Issue by TheHazhir** [ionuttbara/melody_windows#4]
The scripts just did everything as soon as I ran it. I expected to have some choices on what I want it to do, This script is awsome, the only issue is that you can't choose what you want,
1- Windows wallpaper and lockcreen settings stars with a huge delay, around 30 seconds. Any ways to fix this?
2- Windows animations are totally borken. Even when I enable them in windows settings it doesnt work, Is there any way to restore them?
3- The Home page in file explorer is useful for pinning most used folders. Any way to re-enable it?
4- Any ways to enable windows clipboard history?

**Comment by TheHazhir** [comment]
I ended up corrupting my install and had to reinstall windows. One thing I truly apricated about the script was how much it reduced windows footprint. What parts of the script are affect windows' footprint more?

**Comment by ionuttbara** [comment]
Hi.  The release it applies all tweaks which can be in code. So check that the code first.
Second if you want to remove or modifying the exe , download 7-Zip File Manager and run the exe with that. You can add , remove files just like a folder or archive.
Third i respond for listed issues:
1. Wallpaper and lockscreen delays was observed recently. i am working for a fix (maybe something about WindowsConsumerFeatures disablation, seen that in 2 versions of Windows: Windows 8.1 and Windows 10 22H2).
2. The animations are not broken are disabled via Accessibility Setting. To revert, First Go to Settings -> Accesibility and check off Turn off animations.
3. The Home page in Explorer is removed together with Libraries , Previous Versions and Quick Access. That thing is classified for *blotware*. But easy, you can modify the exe end remove "Remove Quick Access.reg", "Remove Libraries.reg" etc. from the downloaded exe and opened with 7-Zip.
4. Yeah, these are applied by a policy tweak 
```
[HKEY_CURRENT_USER\Software\Microsoft\Clipboard]
"EnableClipboardHistory"=dword:00000001

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PolicyManager\default\Experience\AllowClipboardHistory]
"value"=-

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System]
"AllowCrossDeviceClipboard"=-
"AllowClipboardHistory"=-
```

P.S.: If you have any questions or problems feel free to ask!

**Comment by ionuttbara** [comment]
the executable doesn't remove any components so it disables hibernation (some gb free) and force windows to work without Reserved Storage (that's why you get 7 GB free of space) and disables Pagination (all apps ran into ram , for optimizing disk, and 1-2 GB free).

**Comment by ionuttbara** [comment]
this is the command.
```
powercfg -h off & DISM /Online /Set-ReservedStorageState /State:Disabled & reagentc /disable >nul
```
for page file is registry file.
