### ISSUE TITLE
windows search not working

### ISSUE THREAD

**Issue by officialtaxz2** [ionuttbara/melody_windows#6]
cant use windows search (does not open) in order to look for installed programms etc.

**Comment by officialtaxz2** [comment]
System Restore got "destroyed" aswell. Cant use a old SRP since i get an error 0x80042302

**Comment by hellzerg** [comment]
@officialtaxz2 
What is your Windows version.

Also, did you disable System Restore? If yes, that's why it is not working!
Same for the Disable Search!

**Comment by officialtaxz2** [comment]
I had Windows 10 ltsc IoT. System restore as well as search was working
(enabled) before perfectly fine.
After the script, both were not working.
I mentioned the error I've got before (refering to system restore).

Furthermore, to Windows Search, which I was not able to use, I was also not
able to use the search bar in my settings app?

So in the end I decided to reinstall my windows, and now I'm fine again.
But I will not run this one more time :P

**Comment by renatin77** [comment]
The same thing happened to me, this script messed up my windows

**Comment by ionuttbara** [comment]
the service WSearch is disabled. Enable in services.msc by changing startup to automatic and start the service.

**Comment by ionuttbara** [comment]
=

> System Restore got "destroyed" aswell. Cant use a old SRP since i get an error 0x80042302

at the part updated version is not removing SENS and EventSystem anymore.

**Comment by evlo** [comment]
> the service WSearch is disabled. Enable in services.msc by changing startup to automatic and start the service.

Lie,
![image](https://github.com/ionuttbara/melody_windows/assets/8813196/68997cc4-94de-4fdd-8aca-76e8f6f1e30c)
