### ISSUE TITLE
Integrations not installing

### ISSUE THREAD

**Issue by Disbone** [ionuttbara/melody_windows#7]
At the last stage of the installation, a powershell window appears and then immediately closes with some red lines as output, I'd suppose those are the integrations trying to download but failing to. After the computer restarts after the powershell window closing, Ditto, EarTrumpet and Start All back were not installed.

**Comment by ionuttbara** [comment]
diito, eartrumpet and StartAllBack are removed in newer versions.

**Comment by ionuttbara** [comment]
of the script.
